version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000" # accessible uniquement depuis LAN si pare-feu configuré
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env-prod
    depends_on:
      - mongo
    networks:
      - digitalab-net

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - digitalab-net # pas exposé à l'extérieur

volumes:
  mongo-data:

networks:
  digitalab-net:
    driver: bridge
